video:
  model:
    type: dbof
    hidden_dim: 4096
    p_drop: 0.5
    fcn_dim: 2048
    max_len: 150
    n_mixtures: 4
    per_class: false
    frame_se_reduction: 8
    video_se_reduction: 4
  training:
    batch_size: 128
    steps: 100000
    lr: 3e-4
    eps: 1e-6
    weight_decay: 0.1
    ckpt_interval: 10000
